# Generated by Django 4.2.9 on 2024-02-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_job_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_url',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='image_url',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_link',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
