# Generated by Django 4.2.9 on 2024-02-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_job_company_url_alter_job_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='scrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_linkedin_indx', models.IntegerField()),
                ('loc_indeed_indx', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='specific_location',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
