# Generated by Django 4.2.9 on 2024-02-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_scrape_job_specific_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='remote',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
